### ISSUE TITLE
Breaks with `sync' is not implemented by Capistrano::Deploy::SCM::Jenkins (NotImplementedError) on Capistrano 2.9.0

### ISSUE THREAD

**Issue by SysEngArch** [lidaobing/capistrano-scm-jenkins#2]
/usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/recipes/deploy/scm/base.rb:94:in `sync': `sync' is not implemented by Capistrano::Deploy::SCM::Jenkins (NotImplementedError)
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/recipes/deploy/strategy/remote_cache.rb:35:in `update_repository_cache'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/recipes/deploy/strategy/remote_cache.rb:15:in `deploy!'
	from /usr/local/lib/ruby/gems/1.8/gems/railsless-deploy-1.0.2/lib/railsless-deploy.rb:204
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:139:in `instance_eval'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:139:in `invoke_task_directly_without_callbacks'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/namespaces.rb:186:in `send'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/namespaces.rb:186:in `method_missing'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/namespaces.rb:104:in `update_code'
	from /usr/local/lib/ruby/gems/1.8/gems/railsless-deploy-1.0.2/lib/railsless-deploy.rb:185
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:56:in `transaction'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/namespaces.rb:186:in `send'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/namespaces.rb:186:in `method_missing'
	from /usr/local/lib/ruby/gems/1.8/gems/railsless-deploy-1.0.2/lib/railsless-deploy.rb:184
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:139:in `instance_eval'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:139:in `invoke_task_directly_without_callbacks'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/namespaces.rb:186:in `send'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/namespaces.rb:186:in `method_missing'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/namespaces.rb:104:in `update'
	from /usr/local/lib/ruby/gems/1.8/gems/railsless-deploy-1.0.2/lib/railsless-deploy.rb:154
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:139:in `instance_eval'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:139:in `invoke_task_directly_without_callbacks'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:89:in `execute_task'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:46:in `execute_requested_actions_without_help'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:45:in `each'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions_without_help'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/help.rb:19:in `execute_requested_actions'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:34:in `execute!'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:14:in `execute'
	from /usr/local/lib/ruby/gems/1.8/gems/capistrano-2.9.0/bin/cap:4
	from /usr/local/bin/cap:19:in `load'
	from /usr/local/bin/cap:19

**Comment by jeffbyrnes** [comment]
Closing as stale. Please re-open if this is still an issue.
