### ISSUE TITLE
undefined method path for #<StringIO>

### ISSUE THREAD

**Issue by lostintime** [lidaobing/capistrano-scm-jenkins#6]
OpenURI open() returns StringIO (with no path method) if file size is < 10Kb

<code>capistrano-scm-jenkins-0.0.5/lib/capistrano/recipes/deploy/scm/jenkins.rb:43:in `block in checkout': undefined method `path' for #<StringIO:0x007fd743cd1e60> (NoMethodError)</code>

**Comment by jeffbyrnes** [comment]
Closing as stale.
